name: "Library checks"

on: [pull_request]

jobs:
  html_documentation_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Install python packages
        run: |
          pip install --user pytidylib
          pip install --user futures
      - name: Build html tidy
        run: |
          git clone --branch 5.7.28 --depth=1 https://github.com/htacg/tidy-html5.git
          pushd tidy-html5
          cmake .
          make
          sudo make install
          popd
          sudo ldconfig
      - name: Tidy html
        run: python ./.CI/.travis.py tidyHTML ./
      - name: Check html tags
        run: python ./.CI/.travis.py checkTags ./
      - name: Check links
        run: python ./.CI/.travis.py checkLinks ./; fi
  syntax_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Get moparser
        run: git clone --depth=1 https://github.com/modelica-tools/ModelicaSyntaxChecker
      - name: Check file encoding
        run: find . -name '*.mo' -exec bash -c 'iconv -o /dev/null -f utf8 -t utf8 \"{}\" |& sed \"s,^,{}: ,\"' ';' | grep '.'"
      - name: Check syntax
        run: ModelicaSyntaxChecker/Linux64/moparser -v 3.4 -r Complex.mo Modelica ModelicaReference ModelicaServices ModelicaTest ModelicaTestConversion4.mo ModelicaTestOverdetermined.mo ObsoleteModelica4.mo
