name: CI ReSim
on:
  pull_request:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: [ self-hosted, Linux, regression_testing ]  
    steps: 
      - name: Checkout code
        run: | 
            git clone --depth=1 --filter=blob:none --sparse https://github.com/modelica/ModelicaStandardLibrary -b MatthiasBSchaefer_PRTesting
            cd ./ModelicaStandardLibrary
            git sparse-checkout set .CI/ReSim
            ./.CI/ReSim/prepare_pr.sh ${{ github.event.number }}
  
  testrun_modelica:
    needs: prepare
    runs-on: [ self-hosted, Linux, regression_testing ]
    environment: 
        name: Report modelica
        url: ${{ vars.LTX_PR_SERVER }}/${{ github.event.number }}/Modelica/report/PR_comparison_report.html
    steps:         
      - name: Run tests modelica      
        run: ./.CI/ReSim/run_pr.sh ${{ github.event.number }} ${{ github.event.pull_request.base.sha }} Modelica {{ vars.LTX_TESTING_TOOLS }}
        
  testrun_modelicatest:
    needs: prepare
    runs-on: [ self-hosted, Linux, regression_testing ]
    environment: 
        name: Report modelicatest
        url: ${{ vars.LTX_PR_SERVER }}/${{ github.event.number }}/ModelicaTest/report/PR_comparison_report.html
    steps:    
      - name: Run tests modelicatest      
        run:  ./.CI/ReSim/run_pr.sh ${{ github.event.number }} ${{ github.event.pull_request.base.sha }} ModelicaTest {{ vars.LTX_TESTING_TOOLS }}
