name: PR_testing
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare:
    runs-on: self-hosted   
    steps: 
      - name: checkout_pr_repo
        run: /shared_data/run_scripts/prepare_pr.sh ${{ github.event.number }}
  
  testrun_modelica:
    needs: prepare
    runs-on: self-hosted
    environment: 
        name: test
        url: https://serv.ltx.de/prs/${{ github.event.number }}/Modelica/PR_comparison_report.html
    steps:         
      - name: run modelica      
        run: /shared_data/run_pr.sh ${{ github.event.number }} ${{ github.event.pull_request.base.sha }} Modelica
        
  testrun_modelicatest:
    needs: prepare
    runs-on: self-hosted
    environment: 
        name: test
        url: https://serv.ltx.de/prs/${{ github.event.number }}/ModelicaTest/PR_comparison_report.html
    steps:    
      - name: run modelicatest      
        run:  /shared_data/run_pr.sh ${{ github.event.number }} ${{ github.event.pull_request.base.sha }} ModelicaTest
