name: CI ReSim
on:
  pull_request:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: [ self-hosted, Linux, regression_testing ]      
    
    steps: 
      - uses: actions/checkout@v6
        with: 
            sparse-checkout: './.CI/ReSim'

      - name: Checkout code in docker
        run: ./.CI/ReSim/prepare_pr.sh ${{ github.event.number }}
  
  testrun_modelica:
    needs: prepare
    runs-on: [ self-hosted, Linux, regression_testing ]
    env:
      PR_SERVER: ${{ secrets.LTX_PR_SERVER }}
      TESTING_TOOLS: ${{ secrets.LTX_TESTING_TOOLS }}
    environment: 
        name: Report modelica
        url: $PR_SERVER/${{ github.event.number }}/Modelica/report/PR_comparison_report.html
    steps:         
      - name: print envs
        run: echo "TESTING_TOOLS=$TESTING_TOOLS"
      - name: Run tests modelica      
        run: ./.CI/ReSim/run_pr.sh ${{ github.event.number }} ${{ github.event.pull_request.base.sha }} Modelica $TESTING_TOOLS
        
  testrun_modelicatest:
    needs: prepare
    runs-on: [ self-hosted, Linux, regression_testing ]
    env:
      PR_SERVER: ${{ secrets.LTX_PR_SERVER }}
      TESTING_TOOLS: ${{ secrets.LTX_TESTING_TOOLS }}
    environment: 
        name: Report modelicatest
        url: $PR_SERVER/${{ github.event.number }}/ModelicaTest/report/PR_comparison_report.html
    steps:    
      - name: Run tests modelicatest      
        run:  ./.CI/ReSim/run_pr.sh ${{ github.event.number }} ${{ github.event.pull_request.base.sha }} ModelicaTest $TESTING_TOOLS
